---
# tasks file for database

- name: Install dependencies for PostgreSQL
  yum: 
    name: "{{ item }}" 
    update_cache: true 
    state: latest
  loop:
    - bash
    - openssl
    - openssl-devel
    #- openssl-doc
  tags: packages

- name: Install PostgreSQL 
  yum: 
    name: "{{ item }}" 
    update_cache: true
    state: installed
  loop:
    - postgresql-server
    - postgresql-contrib
    - postgresql-devel
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: 
    name: postgresql 
    state: started 
    enabled: yes

- name: Create the database specified in vars
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    template: 'template0'
    state: present

- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present

#- name: Ensure user does not have unnecessary permissions
#  become: true
#  become_user: postgres
#  postgresql_user:
#    name: "{{ db_user }}"
#    role_attr_flags: NOSUPERUSER,NOCREATEDB
#    state: present

- name: copy test_script.sql
  copy:
    src: test_script.sql
    dest: /var/lib/pgsql/test_script.sql
    owner: postgres
    group: postgres
    mode: '0777'
    #backup: yes

- name: Add some dummy data to our database
  become: true
  become_user: postgres
  shell: psql "{{ db_name }}" < /var/lib/pgsql/test_script.sql
